AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket 
    
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: captia-test-s3-bucket-test
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:DeleteObject'
            Effect: Deny
            Resource: 'arn:aws:s3:::captia-test-s3-bucket/*'
            Principal: '*'
            Condition:
              ArnNotEquals:
                'aws:PrincipalArn': 'arn:aws:iam::824897301827:root'
          - Action:
              - 's3:DeleteObject'
            Effect: Allow
            Resource: 'arn:aws:s3:::captia-test-s3-bucket/*'
            Principal: 
              AWS : 'arn:aws:iam::824897301827:root'
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket